name = "Demosthenes"
uuid = "245b5d8d-0603-4ecb-8b48-10ace5a1fb20"
license = "MIT"
authors = ["AlgebraicJulia Developer <email@algebraicjulia.org>"]
version = "0.0.1"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"

[compat]
Catlab = "^0.14"
julia = "1.6"
